In [4]:
import pandas as pd
import DateTime

In [62]:
# 데이터 로드
df = pd.read_csv('merged_all_data.csv', encoding='utf-8')
df['date'] = pd.to_datetime(df['날짜'])

# 각 칼럼별 lag 일수 정의
lag_days = {

'연어_거래량(톤)' : 374,
'연어_가격(NOK/kg)' : 32,

'광어_대'  : 64,
'방어(자연)_대_가락' : 5,
'참돔_대_가락' : 1,

'광어_KOSPI' : 136,
'광어_USD/KRW' : 1,
'광어_WTI' : 1,
'광어_VIX' : 399,
'광어_Gold' : 314,
'광어_Silver' : 238,
'광어_MOVE' : 18,

'농어_KOSPI' : 179,
'농어_USD/KRW' : 1,
'농어_WTI' : 100,
'농어_VIX' : 391,
'농어_Gold' : 361,
'농어_Silver' : 290,
'농어_MOVE' : 1,

'대게_KOSPI' : 148,
'대게_USD/KRW' : 90,
'대게_WTI' : 91,
# '대게_VIX' : 
'대게_Gold' : 177,
'대게_Silver' : 177,
# '대게_MOVE' : 

'방어_KOSPI' : 282,
'방어_USD/KRW' : 387,
'방어_WTI' : 399,
'방어_VIX' : 133,
'방어_Gold' : 1,
'방어_Silver' : 1,\
'방어_MOVE' : 381,

'연어_KOSPI' : 329,
'연어_USD/KRW' : 1,
'연어_WTI' : 199,
'연어_VIX' : 399,
'연어_Gold' : 1,
'연어_Silver' : 399,
'연어_MOVE' : 71,

'우럭_KOSPI' : 155,
'우럭_USD/KRW' : 121,
'우럭_WTI' : 14,
'우럭_VIX' : 38,
'우럭_Gold' : 146,
'우럭_Silver' : 125,
# '우럭_MOVE' : 

'참돔_KOSPI' : 399,
'참돔_USD/KRW' : 11,
'참돔_WTI' : 150,
# '참돔_VIX' : 
# '참돔_Gold' : 
# '참돔_Silver' : 
'참돔_MOVE' : 201,
 
'광어_20대' : 250,
'광어_30대' : 317,
'광어_40대' : 330,
'광어_50대' : 395,
'광어_60대이상' : 339,

'농어_20대' : 305,
'농어_30대' : 307,
'농어_40대' : 309,
'농어_50대' : 309,
'농어_60대이상' : 273,

'대게_20대' : 273,
'대게_30대' : 370,
'대게_40대' : 5,
'대게_50대' : 5,
'대게_60대이상' : 5,

'방어_20대' : 22,
'방어_30대' : 26,
'방어_40대' : 256,
'방어_50대' : 256,
'방어_60대이상' : 26,

'연어_20대' : 20,
'연어_30대' : 15,
'연어_40대' : 21,
'연어_50대' : 15,
'연어_60대이상' : 397,

'우럭_20대' : 22,
'우럭_30대' : 354,
'우럭_40대' : 354,
'우럭_50대' : 220,
'우럭_60대이상' : 219,

'참돔_20대' : 197,
'참돔_30대' : 167,
'참돔_40대' : 278,
'참돔_50대' : 193,
'참돔_60대이상' : 14,

# '광어_20대' : 1,
# '광어_30대' : 1,
# '광어_40대' : 1,
# '광어_50대' : 1,
# '광어_60대이상' : 1,

# '농어_20대' : 1,
# '농어_30대' : 1,
# '농어_40대' : 1,
# '농어_50대' : 1,
# '농어_60대이상' : 1,

# '대게_20대' : 1,
# '대게_30대' : 1,
# '대게_40대' : 1,
# '대게_50대' : 1,
# '대게_60대이상' : 1,

# '방어_20대' : 1,
# '방어_30대' : 1,
# '방어_40대' : 1,
# '방어_50대' : 1,
# '방어_60대이상' : 1,

# '연어_20대' : 1,
# '연어_30대' : 1,
# '연어_40대' : 1,
# '연어_50대' : 1,
# '연어_60대이상' : 1,

# '우럭_20대' : 1,
# '우럭_30대' : 1,
# '우럭_40대' : 1,
# '우럭_50대' : 1,
# '우럭_60대이상' : 1,

# '참돔_20대' : 1,
# '참돔_30대' : 1,
# '참돔_40대' : 1,
# '참돔_50대' : 1,
# '참돔_60대이상' : 1,

'광어_기온_22105' : 97,
'광어_수온_22107' : 79,
'광어_습도_22186' : 349,
'광어_파주기_22190' : 103,

'농어_기온_22105' : 103,
'농어_수온_22107' : 81,
'농어_습도_22186' : 333,
'농어_파주기_22190' : 115,

'대게_기온_22105' : 150,
'대게_수온_22188' : 140,
'대게_습도_22188' : 355,
'대게_파주기_22105' : 174,

'방어_기온_22190' : 114,
'방어_수온_22107' : 118,
'방어_습도_22190' : 158,
'방어_파주기_22105' : 191,

'연어_기온_22105' : 394,
'연어_수온_22107' : 341,
'연어_습도_22105' : 8,
'연어_파주기_22190' : 9,

'우럭_기온_22186' : 118,
'우럭_수온_22186' : 113,
'우럭_습도_22190' : 159,
'우럭_파주기_22189' : 172,

'참돔_기온_22190' : 91,
'참돔_수온_22107' : 72,
'참돔_습도_22190' : 115,
'참돔_파주기_22190' : 107


}

# 각 칼럼에 대해 지정된 lag 적용
for col, lag in lag_days.items():
   if col in df.columns:
       df[f'{col}_{lag}'] = df[col].shift(lag)

# 결과 저장
df.to_csv('timelagged_features.csv', index=False, encoding='utf-8')

C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)
C:\Users\user\AppData\Local\Temp\ipykernel_1536\2414516792.py:196: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{col}_{lag}'] = df[col].shift(lag)

In [63]:
df = pd.read_csv('timelagged_features.csv', encoding='utf-8')

In [77]:
df = df.drop(df.columns[0:1], axis=1)
df

,date,연어_거래량(톤)_374,연어_가격(NOK/kg)_32,방어(자연)_대_가락_5,참돔_대_가락_1,광어_KOSPI_136,광어_USD/KRW_1,광어_WTI_1,광어_VIX_399,광어_Gold_314,...,연어_습도_22105_8,연어_파주기_22190_9,우럭_기온_22186_118,우럭_수온_22186_113,우럭_습도_22190_159,우럭_파주기_22189_172,참돔_기온_22190_91,참돔_수온_22107_72,참돔_습도_22190_115,참돔_파주기_22190_107
0,2015-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-03,NaN,NaN,NaN,NaN,NaN,1093.599976,52.689999,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-01-04,NaN,NaN,NaN,NaN,NaN,1093.599976,52.689999,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-05,NaN,NaN,NaN,NaN,NaN,1093.599976,52.689999,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3670,2025-01-18,16016.0,92.15,NaN,NaN,2580.800049,1453.319946,80.040001,12.28,2178.600098,...,NaN,5.920833,24.285714,25.883333,78.875000,3.425000,19.454167,23.412500,88.000000,4.958333
3671,2025-01-19,16016.0,92.15,NaN,NaN,2575.500000,1453.319946,80.040001,12.28,2182.500000,...,NaN,7.083333,23.994118,25.650000,78.583333,3.420833,17.341667,23.187500,89.916667,5.950000
3672,2025-01-20,16016.0,92.15,NaN,NaN,2544.280029,1453.319946,80.040001,12.56,2160.399902,...,NaN,6.987500,24.480000,26.154167,79.958333,3.350000,20.404167,23.145833,92.750000,5.545833
3673,2025-01-21,16016.0,92.15,NaN,NaN,2544.280029,1457.380005,80.040001,12.53,2175.399902,...,NaN,6.004167,25.533333,26.126087,78.916667,3.212500,21.775000,23.062500,89.291667,4.554167
3674,2025-01-22,16016.0,92.15,NaN,NaN,2544.280029,1435.530029,80.040001,13.67,2163.000000,...,NaN,NaN,25.740000,25.441667,80.541667,3.600000,20.987500,22.900000,74.166667,3.929167

In [78]:
df.to_csv('timelagged_features.csv', index=False)

In [82]:
import pandas as pd

def merge_files():
    df1 = pd.read_csv('timelagged_features.csv', encoding='utf-8')
    df2 = pd.read_csv('timelagged_features_1.csv', encoding='utf-8')
    
    # Ensure important columns are preserved
    important_cols = ['date', '연어_거래량(톤)', '연어_가격(NOK/kg)', '광어_대_가락', 
                     '방어(자연)_대_가락', '참돔_대_가락']
    
    # Get remaining columns
    other_cols = list(set(df1.columns).union(set(df2.columns)) - set(important_cols))
    
    # Combine with important columns first
    cols = important_cols + sorted(other_cols)
    
    merged_df = pd.DataFrame(columns=cols)
    
    for col in cols:
        if col in df1.columns and col in df2.columns:
            merged_df[col] = df1[col].combine_first(df2[col])
        elif col in df1.columns:
            merged_df[col] = df1[col]
        elif col in df2.columns:
            merged_df[col] = df2[col]
    
    output_file = 'final_timelagged_features.csv'
    merged_df.to_csv(output_file, index=False, encoding='utf-8')
    print(f'Created {output_file} with {len(merged_df.columns)} columns')
    print("\nFirst few columns:", merged_df.columns[:10].tolist())
	
    return merged_df

merged_df = merge_files()

Created final_timelagged_features.csv with 151 columns

First few columns: ['date', '연어_거래량(톤)', '연어_가격(NOK/kg)', '광어_대_가락', '방어(자연)_대_가락', '참돔_대_가락', '광어_20대_1', '광어_20대_250', '광어_30대_1', '광어_30대_317']

In [83]:
# 어종별 분류 

def split_by_fish():
    df = pd.read_csv('final_timelagged_features.csv', encoding='utf-8')
    fish_types = ['광어', '농어', '대게', '방어', '연어', '우럭', '참돔']
    
    for fish in fish_types:
        # Get date and fish-specific columns
        fish_cols = ['date'] + [col for col in df.columns if fish in col]
        fish_df = df[fish_cols]
        
        output_file = f'{fish}_timelagged_features.csv'
        fish_df.to_csv(output_file, index=False, encoding='utf-8')
        print(f'Created {output_file} with {len(fish_cols)} columns')

split_by_fish()

Created 광어_timelagged_features.csv with 23 columns
Created 농어_timelagged_features.csv with 22 columns
Created 대게_timelagged_features.csv with 20 columns
Created 방어_timelagged_features.csv with 24 columns
Created 연어_timelagged_features.csv with 26 columns
Created 우럭_timelagged_features.csv with 21 columns
Created 참돔_timelagged_features.csv with 21 columns